#Spring
spring:
  profiles:
    active: "local"

---
spring:
  config:
    activate:
      on-profile: local

core:
  api:
    url: "http://localhost:8090/getWinning"
    pool:
      size: 24
    rounds: 10000

server:
  port: 8090